# code: language=ansible
---
- name: Update all nodes
  hosts: all
  become: true
  roles:
    - debian
    # - configure home directory; check vcsh, move .ssh .gnupg out of the way, etc   # TODO
    - rooted # make this conditional when needed

- name: Update AWS instances
  hosts: aws
  become: true
  roles:
    - aws
