# code: language=ansible

# - name: Attempt to configure release in apt sources.list
#   ansible.builtin.lineinfile:
#     path: /etc/apt/sources.list.d/debian.sources
#     search_string: "Suites:"
#     line: "Suites: {{ debian_release }}"

- name: Set release in default sources.list (old-style)
  when: debian_mirror is not defined
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^deb(-src)? ([a-z/\.:]+) (a-z+) (.*)'
    replace: "deb\\1 \\2 {{ debian_release }}' \\3"

- name: Configure debian mirror/release
  when: debian_mirror is defined
  block:
    - name: Install debian.sources
      ansible.builtin.template:
        force: true
        mode: u+rw,go+r
        owner: root
        group: root
        src: debian.sources
        dest: /etc/apt/sources.list.d/debian.sources

    - name: Create mirror directory
      ansible.builtin.file:
        recurse: true
        state: directory
        path: /etc/apt/mirrors
        mode: u+rwx,go+rx

    - name: Write apt mirror file
      ansible.builtin.copy:
        dest: /etc/apt/mirrors/debian.list
        mode: u+rw,go+r
        content: "{{ debian_mirror }}"

    - name: Comment out default sources.list
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '^[\d]*([^#].+)$'
        replace: '# \1'

- name: Update package cache
  ansible.builtin.apt:
    force_apt_get: true
    default_release: "{{ debian_release }}"
    update_cache: true

- name: Upgrade/clean packages
  ansible.builtin.apt:
    force_apt_get: true
    default_release: "{{ debian_release }}"
    autoclean: true
    autoremove: true
    clean: true
    upgrade: full

- name: Install common Debian packages
  ansible.builtin.apt:
    force_apt_get: true
    default_release: "{{ debian_release }}"
    name:
      - fortune
      - vim
      - screen
      - tmux
      - ddate
      - vcsh
      - cowsay
      - etckeeper
      - tox
      - twine
      - taskwarrior
      - python3-botocore
      - python3-boto3
      - python-is-python3
      - python3-venv
      - fortunes
      - fortunes-debian-hints
      - fortunes-bofh-excuses
      - multitail
      - dstat
      - htop
      - aptitude

- name: Additional packages
  when: extra_packages is defined
  block:
    - name: List extra packages
      ansible.builtin.debug:
        msg:
          - "extra_packages: {{ extra_packages }}"
    - name: Install extra packages
      ansible.builtin.apt:
        force_apt_get: true
        default_release: "{{ debian_release }}"
        name: "{{ extra_packages }}"

- name: Install graphical Debian packages
  ansible.builtin.include_tasks: graphical.yml
