- name: Install AWS-specific packages
  ansible.builtin.apt:
    force_apt_get: true
    install_recommends: true
    name:
#      - awscli
      - python3-boto*

- name: Install Python libraries
  ansible.builtin.pip:
    virtualenv: "{{ system_virtualenv }}"
    name:
      - boto3
      - ec2-metadata

- name: Installing AWS python modules
  tags: python
  ansible.builtin.pip:
    virtualenv: "{{ system_virtualenv }}"
    virtualenv_python: python3
    name:
      - boto
      - boto3
      - ec2_metadata

- name: Install update_r53.py
  ansible.builtin.copy:
    mode: 0755
    src: update_r53.py
    dest: /usr/local/bin/

- name: Install update_r53.service
  ansible.builtin.copy:
    mode: 0644
    src: update_r53.service
    dest: /etc/systemd/system

- name: Enable/restart update_r53 service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    state: restarted
    name: update_r53
